build_script:
- ps: .\build.ps1

test: off

image: Visual Studio 2019

artifacts:
- path: .\artifacts\releases
  name: $(APPVEYOR_PROJECT_NAME).v$(APPVEYOR_BUILD_VERSION)
- path: .\artifacts\nuget\*.nupkg

environment:
  # to set encrypted variable: Go to "Settings" -> "Encrypt YAML" page in account menu
  gh_token:
    secure: LspLx0+75147+2KRJW+KiFWsj9RmBTaEeY+AJe0G9YsdYFWZIadU/xufjdP8aOd+

branches:
  # whitelist
  only:
    - master
    - production
    - develop
    - beta
    - /release/.*/
    - /hotfix/.*/
  # blacklist
  except:
    - gh-pages

notifications:
  # Email
  - provider: Email
    to:
      - lfsmgs@gmail.com
    on_build_success: true
    on_build_failure: true