build_script:
- ps: .\build.ps1

test: on

image: Visual Studio 2017

# artifacts configuration
artifacts:
- path: .\artifacts\releases
  name: $(APPVEYOR_PROJECT_NAME).v$(APPVEYOR_BUILD_VERSION)

# environment variables
# environment:
#   # this is how to set encrypted variable. Go to "Settings" -> "Encrypt YAML" page in account menu to encrypt data.
#   my_secure_var1:
#     secure: FW3tJ3fMncxvs58/ifSP7w==

# branches to build
branches:
  # whitelist
  only:
    - master
    - production
    - appveyor
  # blacklist
  except:
    - gh-pages

# notifications
notifications:
  # Email
  - provider: Email
    to:
      - lfsmgs@gmail.com
    on_build_success: true
    on_build_failure: true