build_script:
- ps: .\build.ps1

test: off

image: Visual Studio 2017

# artifacts configuration
artifacts:
- path: .\artifacts

# branches to build
branches:
  # whitelist
  only:
    - master
    - production
  # blacklist
  except:
    - gh-pages

# notifications
notifications:
  # Email
  - provider: Email
    to:
      - lfsmgs@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
